# Generated by Django 6.0.5 on 2026-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
