# Generated by Django 6.0.5 on 2026-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ky', models.CharField(max_length=200)),
                ('full_name_ru', models.CharField(max_length=200)),
                ('full_name_en', models.CharField(max_length=200)),
                ('bio_ky', models.TextField(blank=True)),
                ('bio_ru', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('subject_ky', models.CharField(max_length=100)),
                ('subject_ru', models.CharField(max_length=100)),
                ('subject_en', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='teachers/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'full_name_ru'],
            },
        ),
    ]
