# Generated by Django 6.0.5 on 2026-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
