# Generated by Django 6.0.5 on 2026-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ky', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_ky', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='achievements/')),
                ('value', models.CharField(help_text="e.g. '200+', '8+', '50'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('text_ky', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(help_text='ЖРТ/ОРТ score achieved')),
                ('video_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='reviews/')),
                ('year', models.PositiveIntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-score'],
            },
        ),
    ]
