# Generated by Django 6.0.5 on 2026-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='1-5 stars')),
                ('course_taken', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Күтүүдө / Pending'), ('approved', 'Жарыяланды / Approved'), ('rejected', 'Четке кагылды / Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes, not shown publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Feedback',
                'verbose_name_plural': 'Student Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
