# Generated by Django 6.0.5 on 2026-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
