# Generated by Django 6.0.5 on 2026-05-14 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_achievement_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='rating',
            field=models.PositiveIntegerField(default=5, help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
