# Generated by Django 6.0.5 on 2026-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
