# Generated by Django 6.0.5 on 2026-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ky', models.CharField(max_length=300)),
                ('title_ru', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('content_ky', models.TextField()),
                ('content_ru', models.TextField()),
                ('content_en', models.TextField()),
                ('category', models.CharField(choices=[('promo', 'Акция / Promotion'), ('course', 'Жаңы курс / New Course'), ('exam', 'ЖРТ жаңылыктары / Exam News'), ('general', 'Жалпы / General')], default='general', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
