# Generated by Django 6.0.5 on 2026-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
